name: Deploy app using EB

on:
  workflow_call:
    inputs:
      to:
        required: true
        type: string

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    env:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Output
        run: |
          echo "Input=${{ inputs.to }}, 
          echo "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}", aws_secret_access_key_env=${{ env.AWS_ACCESS_KEY_ID }}"
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}", aws_secret_access_key_env=${{ env.AWS_SECRET_ACCESS_KEY }}
