name: Scala CI

on:
  workflow_call:
    inputs:
      example:
        required: true
        type: string
    secrets:
      hidden:
        required: true
      another:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      abc: ${{ secrets.hidden }}
      def: ${{ secrets.another }}
    steps:
      - run: echo "Run id=${{ github.run_id }}, run num=${{ github.run_number }}"
      - run: echo "Input=${{ inputs.example }}, secret=${{ secrets.hidden }}, env=${{ env.abc }}, ${{ env.def }}"
