name: Scala CI

on:
  push:
    branches:
      - "sample-pr-branch"

env:
  passedEnv: environment-variable

jobs:
  call-workflow:
    uses: scottmartin924/zio-http-sample/.github/workflows/called.yml@sample-pr-branch
    with:
      example: variable1
    secrets: inherit
