name: Scala CI

on:
  push:
    branches:
      - "sample-pr-branch"

jobs:
  call-workflow:
    uses: scottmartin924/zio-http-sample/.github/workflows/called.yml
    env:
      passedEnv: environment-variable
    with:
      example: variable1
    secrets:
      hidden: ${{ secrets.SAMPLE }}
